# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gabemartinez.github.io/" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: Gabriel Martinez
  avatar: avatar.png
  gravatar: # Email MD5 hash
  description: "Gabriel Martinez" # used by search engines

  # Header and footer text
  header_text: >
     <p>Hi. Welcome to my personal space on the web.</p>

  footer_text: >
   Produced with help from <a href="http://jekyllrb.com">Jekyll</a> with <a href="https://rohanchandra.github.io/project/type/">Type Theme</a> and hosted on <a href="https://github.com/gabemartinez/gabemartinez.github.io">Github Pages</a>.

  # Icons
  rss: false
  email_address: "hi@martinezgabriel.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: "gabemartinez"
  google_plus:
  instagram:
  linkedin: "http://linkedin.com/in/martinezg"
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "gabrielmartinez"
  wordpress:
  youtube:

  # Scripts
  google_analytics: "UA-60957508-1"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "More"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"

# PAGINATION
paginate: 3
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed
